import {useCallback,useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import Card from '../../components/atoms/Card'
import OperatorShell from '../../components/operator/OperatorShell'
import {useAuth} from '../../context/authStore'
import {useAppConfig} from '../../context/appConfigStore'
import * as api from '../../services/healthService'

const clock=value=>new Date(value).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})

export default function DentalOperatorDashboard(){
 const{user}=useAuth();const{config}=useAppConfig();const capabilities=useMemo(()=>new Set(config?.capabilities||[]),[config]);const functions=useMemo(()=>new Set(config?.user?.functions?.map(x=>x.code)||[]),[config]);const reception=functions.has('dental-reception');const dentist=functions.has('dentist')
 const[patients,setPatients]=useState([]);const[appointments,setAppointments]=useState([]);const[treatments,setTreatments]=useState([]);const[operations,setOperations]=useState([]);const[error,setError]=useState('');const[busy,setBusy]=useState('')
 const load=useCallback(async()=>{try{const[p,a,t,o]=await Promise.all([capabilities.has('patients.read')?api.getPatients():[],capabilities.has('appointments.read')?api.getHealthAppointments():[],capabilities.has('dental.treatments.read')?api.getDentalTreatments():[],capabilities.has('appointments.read')?api.getDentalOperations():[]]);setPatients(p);setAppointments(a);setTreatments(t);setOperations(o);setError('')}catch(e){setError(e.message)}},[capabilities])
 useEffect(()=>{queueMicrotask(load);const timer=setInterval(load,15000);return()=>clearInterval(timer)},[load])
 const today=new Date().toLocaleDateString('en-CA'),todayItems=useMemo(()=>appointments.filter(x=>new Date(x.startsAt).toLocaleDateString('en-CA')===today).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)),[appointments,today]);const checked=new Set(operations.map(x=>x.appointment?.id).filter(Boolean))
 const change=async(item,status)=>{setBusy(item.id);setError('');try{await api.updateHealthAppointment(item.id,{status});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const checkIn=async item=>{setBusy(item.id);setError('');try{await api.checkInDentalAttention({patientId:item.patient.id,appointmentId:item.id,dentistId:item.professionalId||null,reason:item.reason});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const actions=[['patients.read','/pos/dental/patients','personal_injury','Pacientes'],['appointments.read','/pos/dental/appointments','calendar_month','Agenda'],['dental.billing.read','/pos/dental/dental-billing','payments','Cobros']].filter(([permission])=>capabilities.has(permission))
 return <OperatorShell title={`Hola, ${user.name}`} subtitle={reception?'Controla llegadas, agenda y pacientes enviados a caja.':'Tu jornada clínica y los pacientes asignados.'}>
  {error?<div className="mb-4 rounded-xl bg-error-container p-3 text-sm text-error">{error}</div>:null}
  <div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><span className="material-symbols-outlined text-primary">today</span><p className="mt-2 text-3xl font-bold">{todayItems.length}</p><p className="text-sm text-on-surface-variant">Citas de hoy</p></Card><Card className="p-4"><span className="material-symbols-outlined text-primary">groups</span><p className="mt-2 text-3xl font-bold">{patients.length}</p><p className="text-sm text-on-surface-variant">{dentist?'Pacientes clínicos':'Pacientes registrados'}</p></Card><Card className="p-4"><span className="material-symbols-outlined text-primary">medical_services</span><p className="mt-2 text-3xl font-bold">{reception?operations.filter(x=>x.status==='ready_for_payment').length:treatments.filter(x=>!['completed','cancelled'].includes(x.status)).length}</p><p className="text-sm text-on-surface-variant">{reception?'Pendientes de cobro':'Tratamientos activos'}</p></Card></div>
  <div className="mt-5 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><Card className="overflow-hidden"><div className="border-b p-4"><h2 className="text-lg font-bold">Agenda de hoy</h2><p className="text-sm text-on-surface-variant">{reception?'Confirma y registra la llegada sin salir de esta pantalla.':'Sólo se muestran tus citas asignadas.'}</p></div><div className="grid gap-2 p-4">{todayItems.map(x=><article className="rounded-xl border border-outline-variant p-3" key={x.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{x.patient.firstName} {x.patient.lastName}</b><p className="text-sm text-on-surface-variant">{clock(x.startsAt)} · {x.specialty}</p><span className="mt-2 inline-block rounded-full bg-primary-fixed px-2 py-1 text-xs font-bold text-primary">{x.status}</span></div>{reception?<div className="flex flex-wrap justify-end gap-2">{x.status==='scheduled'?<button className="rounded-lg border px-3 py-2 text-xs font-bold text-primary" disabled={busy===x.id} onClick={()=>change(x,'confirmed')} type="button">Confirmar</button>:null}{['scheduled','confirmed'].includes(x.status)&&!checked.has(x.id)?<button className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-white" disabled={busy===x.id} onClick={()=>checkIn(x)} type="button">Registrar llegada</button>:null}{['scheduled','confirmed'].includes(x.status)?<button className="rounded-lg border border-error px-3 py-2 text-xs font-bold text-error" disabled={busy===x.id} onClick={()=>change(x,'no_show')} type="button">No asistió</button>:null}</div>:<Link className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-white" to="/pos/dental/patients">Abrir expediente</Link>}</div></article>)}{!todayItems.length?<p className="p-6 text-center text-on-surface-variant">No tienes citas para hoy.</p>:null}</div></Card><Card className="p-4"><h2 className="text-lg font-bold">Herramientas</h2><div className="mt-3 grid gap-2">{actions.map(([,to,icon,label])=><Link className="flex min-h-12 items-center gap-3 rounded-xl border px-3 font-bold hover:border-primary hover:text-primary" key={to} to={to}><span className="material-symbols-outlined">{icon}</span>{label}</Link>)}</div></Card></div>
 </OperatorShell>
}
