import { useCallback, useEffect, useMemo, useState } from 'react'
import Card from '../../components/atoms/Card'
import EmptyState from '../../components/molecules/EmptyState'
import OperatorShell from '../../components/operator/OperatorShell'
import { getHospitalityStaffDashboard, getHospitalitySummary, getHospitalityWorkOrders } from '../../services/hospitalityService'

const departments={housekeeping:'Limpieza',maintenance:'Mantenimiento',security:'Seguridad',laundry:'Lavandería',kitchen:'Cocina',purchasing:'Compras','customer-service':'Atención al cliente','room-service':'Room service'}
export default function HospitalitySupervisorWorkspace(){
 const[summary,setSummary]=useState(null);const[staff,setStaff]=useState(null);const[orders,setOrders]=useState([]);const[error,setError]=useState('')
 const load=useCallback(async()=>{try{const[s,d,o]=await Promise.all([getHospitalitySummary(),getHospitalityStaffDashboard(),getHospitalityWorkOrders()]);setSummary(s);setStaff(d);setOrders(o);setError('')}catch(e){setError(e.message)}},[])
 useEffect(()=>{queueMicrotask(load);const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},5000);return()=>clearInterval(timer)},[load])
 const active=useMemo(()=>orders.filter(item=>['pending','assigned','in_progress'].includes(item.status)),[orders])
 return <OperatorShell subtitle="Monitorea ocupación, retrasos y trabajo de todas las áreas sin acceder a configuración o suscripción." title="Supervisión hotelera">{error?<EmptyState action={{children:'Reintentar',onClick:load}} description={error} icon="cloud_off" title="No se pudo cargar la supervisión"/>:<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Disponibles',summary?.available||0,'bed'],['Ocupadas',summary?.occupied||0,'hotel'],['Tareas activas',active.length,'assignment'],['Limpiezas atrasadas',staff?.overdue||0,'warning']].map(item=><Card className="p-4" key={item[0]}><span className="material-symbols-outlined text-primary">{item[2]}</span><b className="mt-2 block text-3xl">{item[1]}</b><span className="text-sm text-on-surface-variant">{item[0]}</span></Card>)}</div><section className="mt-5 overflow-hidden rounded-2xl border border-outline-variant bg-white"><header className="border-b border-outline-variant p-4"><h2 className="text-lg font-bold">Operación en curso</h2><p className="text-sm text-on-surface-variant">Responsables, áreas y prioridades activas.</p></header><div className="divide-y divide-outline-variant">{active.map(order=><article className="grid gap-2 p-4 sm:grid-cols-[1fr_160px_160px]" key={order.id}><div><b>{order.title}</b><p className="text-sm text-on-surface-variant">{order.room?`Habitación ${order.room.number}`:'Operación general'}</p></div><span className="text-sm font-bold text-primary">{departments[order.functionCode]||order.functionCode}</span><span className="text-sm">{order.assignedTo?.name||'Sin asignar'} · {order.status}</span></article>)}{!active.length?<p className="p-8 text-center text-sm text-on-surface-variant">No hay órdenes activas.</p>:null}</div></section></>}</OperatorShell>
}
