import { useCallback, useEffect, useMemo, useState } from 'react'
import Button from '../../components/atoms/Button'
import Card from '../../components/atoms/Card'
import EmptyState from '../../components/molecules/EmptyState'
import OperatorShell from '../../components/operator/OperatorShell'
import { formatCurrency } from '../../data/dashboard'
import { getHospitalityCashierAccounts, getRoomCharges } from '../../services/hospitalityService'
import HotelCheckoutModal from '../hospitality/HotelCheckoutModal'

export default function HospitalityCashierWorkspace(){const[accounts,setAccounts]=useState([]);const[charges,setCharges]=useState([]);const[selected,setSelected]=useState(null);const[error,setError]=useState('');const load=useCallback(async()=>{try{const[a,c]=await Promise.all([getHospitalityCashierAccounts(),getRoomCharges()]);setAccounts(a);setCharges(c);setError('')}catch(e){setError(e.message)}},[]);useEffect(()=>{queueMicrotask(load);const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},5000);return()=>clearInterval(timer)},[load]);const total=useMemo(()=>accounts.reduce((sum,item)=>sum+Number(item.total)+charges.filter(c=>c.reservationId===item.id).reduce((value,c)=>value+Number(c.total),0),0),[accounts,charges]);return <OperatorShell subtitle="Cobra estancias y consumos finalizados por Recepción y las áreas de servicio." title="Caja hotelera">{error?<EmptyState action={{children:'Reintentar',onClick:load}} description={error} icon="cloud_off" title="No se pudo cargar caja"/>:<><div className="mb-5 grid gap-3 sm:grid-cols-2"><Card className="p-4"><span className="material-symbols-outlined text-primary">pending_actions</span><b className="mt-2 block text-3xl">{accounts.length}</b><span className="text-sm text-on-surface-variant">Cuentas hospedadas</span></Card><Card className="p-4"><span className="material-symbols-outlined text-primary">payments</span><b className="mt-2 block text-3xl">{formatCurrency(total)}</b><span className="text-sm text-on-surface-variant">Total estimado pendiente</span></Card></div><div className="grid gap-3 lg:grid-cols-2">{accounts.map(item=>{const consumption=charges.filter(c=>c.reservationId===item.id).reduce((sum,c)=>sum+Number(c.total),0);return <Card className="p-4" key={item.id}><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-primary">Habitación {item.room.number}</p><h2 className="text-lg font-bold">{item.guest.name}</h2><p className="text-sm text-on-surface-variant">Alojamiento {formatCurrency(item.total)} · Consumos {formatCurrency(consumption)}</p></div><b className="text-xl text-primary">{formatCurrency(Number(item.total)+consumption)}</b></div><Button className="mt-4" icon="payments" onClick={()=>setSelected(item)}>Cobrar cuenta</Button></Card>})}{!accounts.length?<EmptyState description="Recepción todavía no tiene cuentas hospedadas para cobrar." icon="task_alt" title="Caja al día"/>:null}</div></>}{selected?<HotelCheckoutModal charges={charges.filter(c=>c.reservationId===selected.id)} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);load()}} reservation={selected}/>:null}</OperatorShell>}
