import { useEffect, useMemo, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import Button from '../../components/atoms/Button'
import Card from '../../components/atoms/Card'
import Input from '../../components/atoms/Input'
import Select from '../../components/atoms/Select'
import EmptyState from '../../components/molecules/EmptyState'
import OperatorShell from '../../components/operator/OperatorShell'
import { formatCurrency } from '../../data/dashboard'
import { useOperatorProducts } from '../../hooks/useOperatorProducts'
import { useToast } from '../../hooks/useToast'
import { createOperatorSale } from '../../services/operatorService'

const digitsOnly = (event) => { event.currentTarget.value = event.currentTarget.value.replace(/\D/g, '') }

export default function OperatorSale() {
  const { products, loading, error, retry } = useOperatorProducts(); const { showToast } = useToast(); const navigate = useNavigate(); const location = useLocation()
  const [query, setQuery] = useState(''); const [cart, setCart] = useState({}); const [favorites, setFavorites] = useState([]); const [recent, setRecent] = useState([]); const [checkout, setCheckout] = useState(false); const [documentType, setDocumentType] = useState('boleta'); const [paymentMethod, setPaymentMethod] = useState('cash'); const [amountReceived, setAmountReceived] = useState(''); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState(''); const searchRef = useRef(null)
  useEffect(() => { const duplicate = location.state?.duplicate; if (duplicate?.length && products.length) { const next = {}; duplicate.forEach((line) => { const product = products.find((p) => p.id === line.productId); if (product) next[product.id] = Math.min(line.quantity, product.stock) }); queueMicrotask(() => setCart(next)); navigate(location.pathname, { replace: true, state: null }) } }, [location.pathname, location.state, navigate, products])
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return products.filter((p) => p.stock > 0 && (!q || [p.name, p.sku, p.barcode, p.category].some((v) => String(v || '').toLowerCase().includes(q)))) }, [products, query])
  const lines = products.filter((p) => cart[p.id] > 0); const total = lines.reduce((sum, p) => sum + p.price * cart[p.id], 0)
  const add = (product) => { setCart((current) => ({ ...current, [product.id]: Math.min((current[product.id] || 0) + 1, product.stock) })); setRecent((current) => [product.id, ...current.filter((id) => id !== product.id)].slice(0, 6)); setQuery(''); searchRef.current?.focus() }
  const toggleFavorite = (id) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const change = (product, delta) => setCart((current) => { const quantity = Math.max(0, Math.min((current[product.id] || 0) + delta, product.stock)); const next = { ...current }; if (quantity) next[product.id] = quantity; else delete next[product.id]; return next })
  const searchKey = (event) => { if (event.key !== 'Enter') return; event.preventDefault(); const exact = products.find((p) => p.barcode === query.trim() || p.sku.toLowerCase() === query.trim().toLowerCase()); const product = exact || visible[0]; if (product) add(product) }
  const sell = async (event) => { event.preventDefault(); setSaving(true); setFormError(''); const form = new FormData(event.currentTarget); try { const invoice = await createOperatorSale({ documentType: form.get('documentType'), customerName: form.get('customerName'), customerDocument: form.get('customerDocument'), customerAddress: form.get('customerAddress'), paymentMethod: form.get('paymentMethod'), amountReceived: Number(form.get('amountReceived') || 0), lines: lines.map((p) => ({ productId: p.id, quantity: cart[p.id] })) }); setCart({}); setCheckout(false); showToast({ title: 'Venta completada', message: `${invoice.series}-${String(invoice.number).padStart(8, '0')}`, tone: 'success' }); navigate('/pos/invoices') } catch (e) { setFormError(e.message) } finally { setSaving(false) } }
  return <OperatorShell subtitle="Busca, agrega al carrito y cobra sin salir de esta pantalla." title="Nueva venta">
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_380px]">
      <section className="min-w-0"><div className="relative"><span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-outline">barcode_scanner</span><input autoFocus className="min-h-14 w-full rounded-2xl border border-outline-variant bg-white pl-12 pr-4 text-base outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" onChange={(e) => setQuery(e.target.value)} onKeyDown={searchKey} placeholder="Nombre, SKU, codigo de barras o categoria" ref={searchRef} value={query} /></div><p className="mb-3 mt-2 text-xs text-on-surface-variant">Presiona Enter para agregar el primer resultado.</p>
        {loading ? <Card className="h-48 animate-pulse" /> : null}{error ? <EmptyState action={{ children: 'Reintentar', onClick: retry }} description={error} icon="cloud_off" title="Sin conexion" /> : null}
        {recent.length || favorites.length ? <div className="mb-3 flex flex-wrap gap-2">{favorites.map((id) => { const product = products.find((p) => p.id === id); return product ? <button className="rounded-full bg-primary/10 px-3 py-2 text-xs font-bold text-primary" key={id} onClick={() => add(product)} type="button">★ {product.name}</button> : null })}{recent.filter((id) => !favorites.includes(id)).map((id) => { const product = products.find((p) => p.id === id); return product ? <button className="rounded-full bg-white px-3 py-2 text-xs font-bold text-on-surface-variant" key={id} onClick={() => add(product)} type="button">Reciente · {product.name}</button> : null })}</div> : null}
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.slice(0, 30).map((product) => <article className="group overflow-hidden rounded-2xl border border-outline-variant bg-white text-left transition hover:-translate-y-0.5 hover:border-primary hover:shadow-md" key={product.id}><div className="flex aspect-[16/8] items-center justify-center bg-surface-container-low">{product.imageUrl ? <img alt={product.name} className="h-full w-full object-cover" src={product.imageUrl} /> : <span className="material-symbols-outlined text-4xl text-outline">inventory_2</span>}</div><div className="p-3"><p className="truncate text-sm font-bold">{product.name}</p><p className="mt-1 text-xs text-on-surface-variant">Stock {product.stock}</p><div className="mt-3 flex items-center justify-between gap-2"><b className="text-primary">{formatCurrency(product.price)}</b><div className="flex gap-1"><button aria-label={favorites.includes(product.id) ? 'Quitar favorito' : 'Agregar favorito'} className={`material-symbols-outlined rounded-full p-2 ${favorites.includes(product.id) ? 'bg-amber-100 text-amber-700' : 'bg-surface-container-low text-outline'}`} onClick={() => toggleFavorite(product.id)} type="button">star</button><button aria-label={`Agregar ${product.name}`} className="material-symbols-outlined rounded-full bg-primary p-2 text-white" onClick={() => add(product)} type="button">add</button></div></div></div></article>)}</div>
      </section>
      <aside className="h-max min-w-0 rounded-3xl border border-outline-variant bg-white p-4 shadow-sm xl:sticky xl:top-24"><div className="flex items-center justify-between"><h2 className="font-heading text-xl font-bold">Carrito</h2><span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-bold text-primary">{lines.reduce((s, p) => s + cart[p.id], 0)} items</span></div>{!lines.length ? <div className="py-12 text-center"><span className="material-symbols-outlined text-5xl text-outline">shopping_cart</span><p className="mt-2 font-bold">Carrito vacio</p><p className="text-sm text-on-surface-variant">Agrega productos para comenzar.</p></div> : <div className="mt-4 grid max-h-[45vh] gap-2 overflow-y-auto">{lines.map((product) => <div className="rounded-xl bg-surface-container-low p-3" key={product.id}><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{product.name}</p><p className="text-xs text-on-surface-variant">Quedaran {product.stock - cart[product.id]}</p></div><b>{formatCurrency(product.price * cart[product.id])}</b></div><div className="mt-2 flex items-center gap-2"><button aria-label="Restar" className="material-symbols-outlined h-9 w-9 rounded-lg bg-white" onClick={() => change(product, -1)} type="button">remove</button><span className="w-8 text-center font-bold">{cart[product.id]}</span><button aria-label="Sumar" className="material-symbols-outlined h-9 w-9 rounded-lg bg-white" onClick={() => change(product, 1)} type="button">add</button><button className="ml-auto text-xs font-bold text-error" onClick={() => setCart((c) => { const n = { ...c }; delete n[product.id]; return n })} type="button">Eliminar</button></div></div>)}</div>}<div className="mt-4 border-t border-outline-variant pt-4"><div className="flex justify-between text-lg"><span>Total</span><b className="text-2xl text-primary">{formatCurrency(total)}</b></div><Button className="mt-4 w-full" disabled={!lines.length} icon="payments" onClick={() => setCheckout(true)} type="button">Continuar al cobro</Button></div></aside>
    </div>
    {checkout ? <div className="fixed inset-0 z-[80] bg-black/30"><button aria-label="Cerrar cobro" className="absolute inset-0" onClick={() => setCheckout(false)} type="button" /><form className="absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-white p-5 shadow-2xl" onSubmit={sell}><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-primary">Cobro</p><h2 className="font-heading text-2xl font-bold">Confirmar venta</h2></div><button aria-label="Cerrar" className="material-symbols-outlined h-11 w-11 rounded-full bg-surface-container-low" onClick={() => setCheckout(false)} type="button">close</button></div>{formError ? <div className="mt-4 rounded-xl bg-error-container p-3 text-sm text-error">{formError}</div> : null}<div className="mt-5 grid gap-4"><Select label="Comprobante" name="documentType" onChange={(e) => setDocumentType(e.target.value)} value={documentType}><option value="boleta">Boleta</option><option value="factura">Factura</option></Select><Input label="Cliente" maxLength="180" name="customerName" required /><Input inputMode="numeric" label={documentType === 'factura' ? 'RUC (11 dígitos)' : 'DNI (opcional, 8 dígitos)'} maxLength={documentType === 'factura' ? 11 : 8} name="customerDocument" onInput={digitsOnly} pattern={documentType === 'factura' ? '[0-9]{11}' : '[0-9]{8}'} required={documentType === 'factura'} /><Input label="Dirección fiscal" maxLength="240" name="customerAddress" required={documentType === 'factura'} /><Select label="Método de pago" name="paymentMethod" onChange={(e) => setPaymentMethod(e.target.value)} value={paymentMethod}><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="yape">Yape</option><option value="plin">Plin</option><option value="transfer">Transferencia</option></Select>{paymentMethod === 'cash' ? <Input label="Monto recibido" min="0" name="amountReceived" onChange={(e) => setAmountReceived(e.target.value)} step="0.01" type="number" value={amountReceived} /> : <input name="amountReceived" type="hidden" value={total.toFixed(2)} />}</div><Card className="mt-5 p-4"><p className="flex justify-between"><span>Productos</span><b>{lines.reduce((s, p) => s + cart[p.id], 0)}</b></p><p className="mt-2 flex justify-between text-xl"><span>Total</span><b className="text-primary">{formatCurrency(total)}</b></p>{paymentMethod === 'cash' ? <p className="mt-2 flex justify-between text-emerald-700"><span>Vuelto</span><b>{formatCurrency(Math.max(0, Number(amountReceived || 0) - total))}</b></p> : null}</Card><Button className="mt-5 w-full" disabled={saving || (paymentMethod === 'cash' && Number(amountReceived || 0) < total)} icon="check_circle" type="submit">{saving ? 'Procesando...' : 'Confirmar venta'}</Button></form></div> : null}
  </OperatorShell>
}
