import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Badge from '../../components/atoms/Badge'
import Button from '../../components/atoms/Button'
import Card from '../../components/atoms/Card'
import EmptyState from '../../components/molecules/EmptyState'
import Modal from '../../components/molecules/Modal'
import OperatorShell from '../../components/operator/OperatorShell'
import { formatCurrency } from '../../data/dashboard'
import { getOperatorInvoices } from '../../services/operatorService'
import { printInvoice } from '../../utils/invoiceExport'

const number=(x)=>`${x.series}-${String(x.number).padStart(8,'0')}`
function Detail({ invoice,onClose }){return <Modal onClose={onClose} title={`${invoice.documentType==='factura'?'Factura':'Boleta'} ${number(invoice)}`}><article className="p-5 print:p-0"><header className="rounded-2xl bg-primary p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest">Wasita · Comprobante interno</p><div className="mt-3 flex flex-wrap justify-between gap-3"><div><h2 className="font-heading text-2xl font-bold">{number(invoice)}</h2><p className="text-sm text-primary-fixed">{new Date(invoice.issuedAt).toLocaleString('es-PE')}</p></div><Badge tone={invoice.status==='issued'?'success':'danger'}>{invoice.status==='issued'?'Emitido':'Anulado'}</Badge></div></header><section className="mt-4 grid gap-2 rounded-2xl border border-outline-variant p-4 sm:grid-cols-2"><p><b>Cliente:</b> {invoice.customerName}</p><p><b>Documento:</b> {invoice.customerDocument||'Sin documento'}</p><p><b>Pago:</b> {invoice.paymentMethod}</p><p><b>Estado:</b> {invoice.status}</p></section><div className="mt-4 grid gap-2">{invoice.lines.map((line)=><div className="flex justify-between gap-3 rounded-xl bg-surface-container-low p-3" key={line.id}><span>{line.quantity} × {line.productName}</span><b>{formatCurrency(line.total)}</b></div>)}</div><div className="ml-auto mt-5 grid max-w-xs gap-1"><p className="flex justify-between"><span>Subtotal</span><b>{formatCurrency(invoice.subtotal)}</b></p><p className="flex justify-between"><span>IGV</span><b>{formatCurrency(invoice.tax)}</b></p><p className="flex justify-between text-xl"><span>Total</span><b>{formatCurrency(invoice.total)}</b></p></div><div className="mt-5 flex flex-wrap justify-end gap-2 print:hidden"><Button icon="print" onClick={()=>printInvoice(invoice)} type="button" variant="secondary">Imprimir / PDF</Button><div className="flex h-20 w-20 items-center justify-center rounded-xl border border-dashed border-outline text-[10px] text-outline">QR futuro</div></div></article></Modal>}
export default function OperatorInvoices(){const [items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[detail,setDetail]=useState(null);const navigate=useNavigate();const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await getOperatorInvoices())}catch(e){setError(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{queueMicrotask(load)},[load]);return <OperatorShell subtitle="Solo comprobantes emitidos por tu usuario." title="Mis comprobantes">{loading?<Card className="h-32 animate-pulse"/>:null}{error?<EmptyState action={{children:'Reintentar',onClick:load}} description={error} icon="cloud_off" title="No se pudieron cargar"/>:null}{!loading&&!error&&!items.length?<EmptyState action={{children:'Nueva venta',onClick:()=>navigate('/pos/sale')}} description="Tus ventas apareceran aqui." icon="receipt_long" title="Sin comprobantes"/>:null}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((invoice)=><Card className="p-4" key={invoice.id}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{number(invoice)}</p><p className="mt-1 text-xs text-on-surface-variant">{new Date(invoice.issuedAt).toLocaleString('es-PE')}</p></div><Badge tone={invoice.status==='issued'?'success':'danger'}>{invoice.status==='issued'?'Emitido':'Anulado'}</Badge></div><p className="mt-4 truncate text-sm font-bold">{invoice.customerName}</p><p className="mt-1 text-xs text-on-surface-variant">Pago: {invoice.paymentMethod}</p><p className="mt-4 text-2xl font-bold text-primary">{formatCurrency(invoice.total)}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={()=>setDetail(invoice)} type="button" variant="secondary">Ver</Button><Button icon="content_copy" onClick={()=>navigate('/pos/sale',{state:{duplicate:invoice.lines}})} type="button" variant="ghost">Duplicar venta</Button></div></Card>)}</div>{detail?<Detail invoice={detail} onClose={()=>setDetail(null)}/>:null}</OperatorShell>}
