import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Badge from '../../components/atoms/Badge'
import Button from '../../components/atoms/Button'
import Card from '../../components/atoms/Card'
import EmptyState from '../../components/molecules/EmptyState'
import Modal from '../../components/molecules/Modal'
import OperatorShell from '../../components/operator/OperatorShell'
import InvoiceReceiptPreview from '../../components/invoices/InvoiceReceiptPreview'
import { useAppConfig } from '../../context/appConfigStore'
import { formatCurrency } from '../../data/dashboard'
import { getOperatorInvoices } from '../../services/operatorService'
import { printInvoice } from '../../utils/invoiceExport'

const number=(x)=>`${x.series}-${String(x.number).padStart(8,'0')}`
function Detail({ business, invoice,onClose }){return <Modal dialogClassName="max-w-[58rem]" onClose={onClose} title={`${invoice.documentType==='factura'?'Factura':'Boleta'} ${number(invoice)}`}><article className="grid gap-4 p-3 sm:p-5"><InvoiceReceiptPreview business={business} invoice={invoice}/><div className="flex justify-end print:hidden"><Button icon="print" onClick={()=>printInvoice(invoice,business)} type="button" variant="secondary">Imprimir / PDF</Button></div></article></Modal>}
export default function OperatorInvoices(){const {config}=useAppConfig();const business=config?.business||null;const [items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[detail,setDetail]=useState(null);const navigate=useNavigate();const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await getOperatorInvoices())}catch(e){setError(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{queueMicrotask(load)},[load]);return <OperatorShell subtitle="Solo comprobantes emitidos por tu usuario." title="Mis comprobantes">{loading?<Card className="h-32 animate-pulse"/>:null}{error?<EmptyState action={{children:'Reintentar',onClick:load}} description={error} icon="cloud_off" title="No se pudieron cargar"/>:null}{!loading&&!error&&!items.length?<EmptyState action={{children:'Nueva venta',onClick:()=>navigate('/pos/sale')}} description="Tus ventas apareceran aqui." icon="receipt_long" title="Sin comprobantes"/>:null}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((invoice)=><Card className="p-4" key={invoice.id}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{number(invoice)}</p><p className="mt-1 text-xs text-on-surface-variant">{new Date(invoice.issuedAt).toLocaleString('es-PE')}</p></div><Badge tone={invoice.status==='issued'?'success':'danger'}>{invoice.status==='issued'?'Emitido':'Anulado'}</Badge></div><p className="mt-4 truncate text-sm font-bold">{invoice.customerName}</p><p className="mt-1 text-xs text-on-surface-variant">Pago: {invoice.paymentMethod}</p><p className="mt-4 text-2xl font-bold text-primary">{formatCurrency(invoice.total)}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={()=>setDetail(invoice)} type="button" variant="secondary">Ver</Button><Button icon="content_copy" onClick={()=>navigate('/pos/sale',{state:{duplicate:invoice.lines}})} type="button" variant="ghost">Duplicar venta</Button></div></Card>)}</div>{detail?<Detail business={business} invoice={detail} onClose={()=>setDetail(null)}/>:null}</OperatorShell>}
