import { apiBlob,apiDownload,apiRequest } from '../api/httpClient'
const json=(method,body)=>({method,body:JSON.stringify(body)})
const queryString=(filters={})=>{
 const params=new URLSearchParams()
 Object.entries(filters).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")params.set(key,value)})
 const query=params.toString()
 return query?`?${query}`:""
}
export const getPatients=(search='')=>apiRequest(`/health/patients?search=${encodeURIComponent(search)}`)
export const getPatientsPage=(filters={})=>apiRequest(`/health/patients/page${queryString(filters)}`)
export const createPatient=(data)=>apiRequest('/health/patients',json('POST',data))
export const updatePatient=(id,data)=>apiRequest(`/health/patients/${id}`,json('PATCH',data))
export const deactivatePatient=id=>apiRequest(`/health/patients/${id}`,{method:'DELETE'})
export const permanentlyDeletePatient=id=>apiRequest(`/health/patients/${id}/permanent`,{method:'DELETE'})
export const restorePatient=id=>apiRequest(`/health/patients/${id}/restore`,{method:'POST'})
export const getHealthAppointments=()=>apiRequest('/health/appointments')
export const getDentalProfessionals=()=>apiRequest('/health/dental/professionals')
export const getDentalStaffSummary=id=>apiRequest(`/health/dental/staff/${id}/summary`)
export const getDentalNotifications=(unreadOnly=false)=>apiRequest(`/health/dental/notifications${unreadOnly?'?unread_only=true':''}`)
export const readDentalNotification=id=>apiRequest(`/health/dental/notifications/${id}/read`,{method:'POST'})
export const readAllDentalNotifications=()=>apiRequest('/health/dental/notifications/read-all',{method:'POST'})
export const createHealthAppointment=(data)=>apiRequest('/health/appointments',json('POST',data))
export const updateHealthAppointment=(id,data)=>apiRequest(`/health/appointments/${id}`,json('PATCH',data))
export const prepareAppointmentWhatsApp=(id,message='')=>apiRequest(`/health/appointments/${id}/whatsapp-reminder`,json('POST',{message:message||null}))
export const getDentalChart=(patientId)=>apiRequest(`/health/dental/chart?patient_id=${encodeURIComponent(patientId)}`)
export const createDentalChartEntry=(data)=>apiRequest('/health/dental/chart',json('POST',data))
export const updateDentalChartEntry=(id,data)=>apiRequest(`/health/dental/chart/${id}`,json('PATCH',data))
export const exportDentalChart=(patientId,format)=>apiDownload(`/health/dental/chart/export?patient_id=${encodeURIComponent(patientId)}&format=${format}`)
export const previewDentalChartPdf=patientId=>apiBlob(`/health/dental/chart/export?patient_id=${encodeURIComponent(patientId)}&format=pdf`)
export const getDentalTreatments=(patientId='')=>apiRequest(`/health/dental/treatments${patientId?`?patient_id=${encodeURIComponent(patientId)}`:''}`)
export const createDentalTreatment=(data)=>apiRequest('/health/dental/treatments',json('POST',data))
export const updateDentalTreatment=(id,data)=>apiRequest(`/health/dental/treatments/${id}`,json('PATCH',data))
export const adjustDentalTreatmentPrice=(id,data)=>apiRequest(`/health/dental/treatments/${id}/agreed-price`,json('PATCH',data))
export const getDentalClinicalEntries=id=>apiRequest(`/health/dental/clinical-entries?patient_id=${encodeURIComponent(id)}`)
export const createDentalClinicalEntry=data=>apiRequest('/health/dental/clinical-entries',json('POST',data))
export const updateDentalClinicalEntry=(id,data)=>apiRequest(`/health/dental/clinical-entries/${id}`,json('PATCH',data))
export const getDentalPrescriptions=id=>apiRequest(`/health/dental/prescriptions?patient_id=${encodeURIComponent(id)}`)
export const createDentalPrescription=data=>apiRequest('/health/dental/prescriptions',json('POST',data))
export const updateDentalPrescription=(id,data)=>apiRequest(`/health/dental/prescriptions/${id}`,json('PATCH',data))
export const getDentalDocuments=id=>apiRequest(`/health/dental/documents?patient_id=${encodeURIComponent(id)}`)
export const createDentalDocument=data=>apiRequest('/health/dental/documents',json('POST',data))
export const updateDentalDocument=(id,data)=>apiRequest(`/health/dental/documents/${id}`,json('PATCH',data))
export const getDentalConsentTemplates=()=>apiRequest('/health/dental/consents/templates')
export const getDentalConsents=id=>apiRequest(`/health/dental/consents?patient_id=${encodeURIComponent(id)}`)
export const startDentalConsent=data=>apiRequest('/health/dental/consents',json('POST',data))
export const renewDentalConsentQr=id=>apiRequest(`/health/dental/consents/${id}/qr`,json('POST',{}))
export const downloadDentalConsent=id=>apiDownload(`/health/dental/consents/${id}/document`)
export const previewDentalConsent=id=>apiBlob(`/health/dental/consents/${id}/document`)
export const signDentalConsent=data=>apiRequest(`/health/dental/consents/${data.id}/dentist-sign`,json('POST',{signatureDataUrl:data.signatureDataUrl,accepted:true}))
export const deleteDentalConsent=id=>apiRequest(`/health/dental/consents/${id}`,{method:'DELETE'})
export const voidDentalConsent=(id,reason)=>apiRequest(`/health/dental/consents/${id}/void`,json('POST',{reason}))
export const lookupPublicDentalConsent=data=>apiRequest('/health/dental/consents/public/lookup',json('POST',data))
export const signPublicDentalConsent=data=>apiRequest('/health/dental/consents/public/sign',json('POST',data))
export const getDentalProcedures=(options={})=>apiRequest(`/health/dental/procedures${queryString({include_inactive:options.includeInactive?true:undefined})}`)
export const createDentalProcedure=data=>apiRequest('/health/dental/procedures',json('POST',data))
export const updateDentalProcedure=(id,data)=>apiRequest(`/health/dental/procedures/${id}`,json('PATCH',data))
export const updateDentalProcedureStatus=(id,status)=>apiRequest(`/health/dental/procedures/${id}/status`,json('PATCH',{status}))
export const activateDentalProcedure=id=>updateDentalProcedureStatus(id,'active')
export const deactivateDentalProcedure=id=>updateDentalProcedureStatus(id,'inactive')
export const deleteDentalProcedure=id=>apiRequest(`/health/dental/procedures/${id}`,{method:'DELETE'})
export const getDentalPayments=(id='')=>apiRequest(`/health/dental/payments${id?`?patient_id=${encodeURIComponent(id)}`:''}`)
export const createDentalPayment=data=>apiRequest('/health/dental/payments',json('POST',data))
export const getDentalCashSummary=(date)=>apiRequest(`/health/dental/cash-summary${date?`?date=${encodeURIComponent(date)}`:''}`)
export const getDentalCashCalendar=(month)=>apiRequest(`/health/dental/cash-calendar?month=${encodeURIComponent(month)}`)
export const openDentalCashSession=data=>apiRequest('/health/dental/cash-session/open',json('POST',data))
export const createDentalCashMovement=data=>apiRequest('/health/dental/cash-session/movements',json('POST',data))
export const closeDentalCashSession=data=>apiRequest('/health/dental/cash-session/close',json('POST',data))
export const getDentalReceivables=(status='pending')=>apiRequest(`/health/dental/receivables?status=${status}`)
export const getDentalReport=()=>apiRequest('/health/dental/report')
export const getDentalFinancialReport=(period='daily',date='')=>apiRequest(`/health/dental/financial-report?period=${encodeURIComponent(period)}${date?`&date=${encodeURIComponent(date)}`:''}`)
export const getDentalHistory=()=>apiRequest('/health/dental/history')
export const getDentalSupplies=()=>apiRequest('/health/dental/supplies')
export const getDentalConsumptions=id=>apiRequest(`/health/dental/consumptions?patient_id=${encodeURIComponent(id)}`)
export const createDentalAttention=data=>apiRequest('/health/dental/attentions',json('POST',data))
export const checkInDentalAttention=data=>apiRequest('/health/dental/attentions/check-in',json('POST',data))
export const startDentalAttention=data=>apiRequest('/health/dental/attentions/start',json('POST',data))
export const cancelDentalAttention=id=>apiRequest(`/health/dental/attentions/${id}`,json('PATCH',{status:'cancelled'}))
export const getDentalOperations=()=>apiRequest('/health/dental/operations/today')
