import { apiBlob,apiDownload,apiRequest } from '../api/httpClient'
const json=(method,body)=>({method,body:JSON.stringify(body)})
const queryString=(filters={})=>{
 const params=new URLSearchParams()
 Object.entries(filters).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")params.set(key,value)})
 const query=params.toString()
 return query?`?${query}`:""
}
export const getPatients=(search='')=>apiRequest(`/health/patients?search=${encodeURIComponent(search)}`)
export const getPatientsPage=(filters={})=>apiRequest(`/health/patients/page${queryString(filters)}`)
export const createPatient=(data)=>apiRequest('/health/patients',json('POST',data))
export const updatePatient=(id,data)=>apiRequest(`/health/patients/${id}`,json('PATCH',data))
export const deactivatePatient=id=>apiRequest(`/health/patients/${id}`,{method:'DELETE'})
export const permanentlyDeletePatient=id=>apiRequest(`/health/patients/${id}/permanent`,{method:'DELETE'})
export const restorePatient=id=>apiRequest(`/health/patients/${id}/restore`,{method:'POST'})
export const getHealthAppointments=()=>apiRequest('/health/appointments')
export const getDentalProfessionals=()=>apiRequest('/health/dental/professionals')
export const getDentalStaffSummary=id=>apiRequest(`/health/dental/staff/${id}/summary`)
export const getDentalNotifications=(unreadOnly=false)=>apiRequest(`/health/dental/notifications${unreadOnly?'?unread_only=true':''}`)
export const readDentalNotification=id=>apiRequest(`/health/dental/notifications/${id}/read`,{method:'POST'})
export const readAllDentalNotifications=()=>apiRequest('/health/dental/notifications/read-all',{method:'POST'})
export const createHealthAppointment=(data)=>apiRequest('/health/appointments',json('POST',data))
export const updateHealthAppointment=(id,data)=>apiRequest(`/health/appointments/${id}`,json('PATCH',data))
export const prepareAppointmentWhatsApp=(id,message='')=>apiRequest(`/health/appointments/${id}/whatsapp-reminder`,json('POST',{message:message||null}))
export const getDentalChart=(patientId)=>apiRequest(`/health/dental/chart?patient_id=${encodeURIComponent(patientId)}`)
export const createDentalChartEntry=(data)=>apiRequest('/health/dental/chart',json('POST',data))
export const updateDentalChartEntry=(id,data)=>apiRequest(`/health/dental/chart/${id}`,json('PATCH',data))
export const exportDentalChart=(patientId,format)=>apiDownload(`/health/dental/chart/export?patient_id=${encodeURIComponent(patientId)}&format=${format}`)
export const previewDentalChartPdf=patientId=>apiBlob(`/health/dental/chart/export?patient_id=${encodeURIComponent(patientId)}&format=pdf`)
export const getDentalTreatments=(patientId='')=>apiRequest(`/health/dental/treatments${patientId?`?patient_id=${encodeURIComponent(patientId)}`:''}`)
export const createDentalTreatment=(data)=>apiRequest('/health/dental/treatments',json('POST',data))
export const updateDentalTreatment=(id,data)=>apiRequest(`/health/dental/treatments/${id}`,json('PATCH',data))
export const getDentalClinicalEntries=id=>apiRequest(`/health/dental/clinical-entries?patient_id=${encodeURIComponent(id)}`)
export const createDentalClinicalEntry=data=>apiRequest('/health/dental/clinical-entries',json('POST',data))
export const updateDentalClinicalEntry=(id,data)=>apiRequest(`/health/dental/clinical-entries/${id}`,json('PATCH',data))
export const getDentalPrescriptions=id=>apiRequest(`/health/dental/prescriptions?patient_id=${encodeURIComponent(id)}`)
export const createDentalPrescription=data=>apiRequest('/health/dental/prescriptions',json('POST',data))
export const updateDentalPrescription=(id,data)=>apiRequest(`/health/dental/prescriptions/${id}`,json('PATCH',data))
export const getDentalDocuments=id=>apiRequest(`/health/dental/documents?patient_id=${encodeURIComponent(id)}`)
export const createDentalDocument=data=>apiRequest('/health/dental/documents',json('POST',data))
export const updateDentalDocument=(id,data)=>apiRequest(`/health/dental/documents/${id}`,json('PATCH',data))
export const getDentalProcedures=()=>apiRequest('/health/dental/procedures')
export const createDentalProcedure=data=>apiRequest('/health/dental/procedures',json('POST',data))
export const getDentalPayments=(id='')=>apiRequest(`/health/dental/payments${id?`?patient_id=${encodeURIComponent(id)}`:''}`)
export const createDentalPayment=data=>apiRequest('/health/dental/payments',json('POST',data))
export const getDentalReceivables=(status='pending')=>apiRequest(`/health/dental/receivables?status=${status}`)
export const getDentalReport=()=>apiRequest('/health/dental/report')
export const getDentalHistory=()=>apiRequest('/health/dental/history')
export const getDentalSupplies=()=>apiRequest('/health/dental/supplies')
export const getDentalConsumptions=id=>apiRequest(`/health/dental/consumptions?patient_id=${encodeURIComponent(id)}`)
export const createDentalAttention=data=>apiRequest('/health/dental/attentions',json('POST',data))
export const checkInDentalAttention=data=>apiRequest('/health/dental/attentions/check-in',json('POST',data))
export const startDentalAttention=data=>apiRequest('/health/dental/attentions/start',json('POST',data))
export const cancelDentalAttention=id=>apiRequest(`/health/dental/attentions/${id}`,json('PATCH',{status:'cancelled'}))
export const getDentalOperations=()=>apiRequest('/health/dental/operations/today')
