import { apiBlob, apiDownload, apiRequest } from '../api/httpClient'
const json=(method,body)=>({method,body:JSON.stringify(body)})
export const getVeterinarySummary=()=>apiRequest('/veterinary/summary')
export const getPets=(search='')=>apiRequest(`/veterinary/pets?search=${encodeURIComponent(search)}`)
export const createPet=data=>apiRequest('/veterinary/pets',json('POST',data))
export const updatePet=(id,data)=>apiRequest(`/veterinary/pets/${id}`,json('PATCH',data))
export const deactivatePet=id=>apiRequest(`/veterinary/pets/${id}`,{method:'DELETE'})
export const restorePet=id=>apiRequest(`/veterinary/pets/${id}/restore`,json('POST',{}))
export const permanentlyDeletePet=id=>apiRequest(`/veterinary/pets/${id}/permanent`,{method:'DELETE'})
export const getPetRecord=id=>apiRequest(`/veterinary/pets/${id}/record`)
export const getVeterinarySupplies=()=>apiRequest('/veterinary/supplies')
export const getVeterinaryConsumptions=petId=>apiRequest(`/veterinary/consumptions?pet_id=${encodeURIComponent(petId)}`)
export const getVeterinaryProfessionals=()=>apiRequest('/veterinary/professionals')
export const getVeterinaryAppointments=(start='',end='')=>{
 const query=new URLSearchParams()
 if(start)query.set('start',start)
 if(end)query.set('end',end)
 const suffix=query.toString()
 return apiRequest(`/veterinary/appointments${suffix?`?${suffix}`:''}`)
}
export const createVeterinaryAppointment=data=>apiRequest('/veterinary/appointments',json('POST',data))
export const updateVeterinaryAppointment=(id,status)=>apiRequest(`/veterinary/appointments/${id}`,json('PATCH',{status}))
export const prepareVeterinaryAppointmentWhatsApp=(id,message='')=>apiRequest(`/veterinary/appointments/${id}/whatsapp-reminder`,json('POST',{message}))
export const createVeterinaryRecord=data=>apiRequest('/veterinary/records',json('POST',data))
export const updateVeterinaryPayment=(id,payment='paid')=>apiRequest(`/veterinary/records/${id}/payment`,json('PATCH',typeof payment==='string'?{payment_status:payment}:payment))
export const getVeterinaryBilling=(status='pending')=>apiRequest(`/veterinary/billing?status=${status}`)
export const createVeterinaryVaccine=data=>apiRequest('/veterinary/vaccines',json('POST',data))
export const getVeterinaryDocuments=petId=>apiRequest(`/veterinary/documents?pet_id=${encodeURIComponent(petId)}`)
export const createVeterinaryDocument=data=>apiRequest('/veterinary/documents',json('POST',data))
export const deleteVeterinaryDocument=id=>apiRequest(`/veterinary/documents/${id}`,{method:'DELETE'})
export const previewVeterinaryReport=(petId,kind='clinical')=>apiBlob(`/veterinary/pets/${petId}/export?kind=${encodeURIComponent(kind)}&download=false`)
export const downloadVeterinaryReport=(petId,kind='clinical')=>apiDownload(`/veterinary/pets/${petId}/export?kind=${encodeURIComponent(kind)}&download=true`)
